/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package framePackage;

import static framePackage.mainFrame.contentPanel;

/**
 *
 * @author ASUS
 */
public class absensiPanel extends javax.swing.JPanel {

    /**
     * Creates new form absensiPanel
     */
    public absensiPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        buttonCariData = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtJenisExtra = new javax.swing.JTextField();
        buttonEskul = new javax.swing.JButton();
        buttonSaveData = new javax.swing.JButton();
        tabelSiswaAktif = new javax.swing.JScrollPane();
        tableSiswaAktif = new javax.swing.JTable();
        buttonSaveData1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(30, 58, 138));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DATA SISWA AKTIF");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        buttonCariData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonCariData.setText("CARI DATA");
        buttonCariData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariDataActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("JENIS EKSTRAKURIKULER");

        txtJenisExtra.setBackground(new java.awt.Color(204, 204, 204));
        txtJenisExtra.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        txtJenisExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisExtraActionPerformed(evt);
            }
        });

        buttonEskul.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonEskul.setText("CARI EKSTRAKURIKULER");
        buttonEskul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEskulActionPerformed(evt);
            }
        });

        buttonSaveData.setBackground(new java.awt.Color(40, 167, 69));
        buttonSaveData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonSaveData.setForeground(new java.awt.Color(255, 255, 255));
        buttonSaveData.setText("SAVE DATA");
        buttonSaveData.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonSaveData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveDataActionPerformed(evt);
            }
        });

        tableSiswaAktif.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelSiswaAktif.setViewportView(tableSiswaAktif);

        buttonSaveData1.setBackground(new java.awt.Color(40, 167, 69));
        buttonSaveData1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonSaveData1.setForeground(new java.awt.Color(255, 255, 255));
        buttonSaveData1.setText("KEMBALI");
        buttonSaveData1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonSaveData1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveData1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtJenisExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonEskul)
                        .addGap(18, 18, 18)
                        .addComponent(buttonCariData, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(buttonSaveData1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(buttonSaveData, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tabelSiswaAktif, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonEskul, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJenisExtra)
                    .addComponent(buttonCariData, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(tabelSiswaAktif, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSaveData, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSaveData1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCariDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariDataActionPerformed
        // TODO add your handling code here:
        if (txtJenisExtra.getText().isEmpty()) {
            dataAll();
        }
        else {
            data ();
        }
    }//GEN-LAST:event_buttonCariDataActionPerformed

    private void txtJenisExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisExtraActionPerformed
        // TODO add your handling code here:
        txtJenisExtra();
    }//GEN-LAST:event_txtJenisExtraActionPerformed

    private void buttonEskulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEskulActionPerformed
        // TODO add your handling code here:
        new dataExtraForKelola (). setVisible(true);
    }//GEN-LAST:event_buttonEskulActionPerformed

    private void buttonSaveDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveDataActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("simpan Data JTable ke PDF");

        int userSelection = chooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = chooser.getSelectedFile();

            try {
                Document document = new Document ();
                com.itextpdf.text.pdf.PdfWriter.getInstance(document, new FileOutputStream(fileToSave.getAbsolutePath() + ".pdf");
                    document.open();

                    //Font untuk header dan isi
                    Font fontHeader = new Font(Font.FontFmily.HELVETICA, 9, Font.BOLD);
                    Font fontCell = new Font(Font.FontFamily.HELVETICA, 8);

                    //Tambahkan Judul
                    Paragraph title = new Paragraph ;("Daftar Siswa Aktif Ekstrakurikuler"), new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);

                    title.setAlignment(Element.ALIGN CENTER);
                    document.add(title);
                    document.add(new Paragraph("")); //spasi

                    //Buat tabel PDF sesuai jumlah kolom JTable
                    PdfPTable pdfTable = new PdfPTable(tableSiswaAktif.getColumnCount());
                    pdfTable.setWidtingPercentage(100); // tabel full width
                    pdfTable.setSpacingBefore(10f);
                    pdfTable.setSpacingAfter(10f);

                    //Header kolom
                    for (int i = 0;) i < tableSiswaAktif.getColumnt(); i++{
                        PdfPCell cell = new PdfPcell(new Phrase(tabelSiswaAktif.getColumName(i), fontHeader));
                        cell.setHorizontalAligment(Element.ALIGN_CENTER);
                        cell.setBackgroundColor(RuleBasedCollator.LIGHT GRAY);
                        pdfTable.addCell(cell);
                    }
                    //Isi tabel
                    for (int row = 0; row < tabelSiswaAktif.getRowCount(); row++) {
                        for (int col = 0; col < tabelSiswaAktif.getColumnCount(); col++) {
                            Object value = tabelSiswaAktif.getValueAt(row, col);
                            PdfaPCell cell = new PdfPCell(new Phrase(value == null) ?"" : value.toString(), fontCell));
                        cell.setHorizontalAligment(StackTraceElement.ALIGN_LEFT);
                        pdfTable.addCell(cell);
                    }
                }
                document.add(pdfTable);
                document.close();

                JOptionPane.showMessageDialog(this,
                    "Data berhasil disimpan ke PDF:\n" + fileToSave.getAbsolutePath() + ".pdf");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan PDF : " + e.getMessage());
        }

    }//GEN-LAST:event_buttonSaveDataActionPerformed

    private void buttonSaveData1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveData1ActionPerformed
        // TODO add your handling code here:
        contentPanel.removeAll();
        contentPanel.add(new dataSiswaAktifPanel());
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_buttonSaveData1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCariData;
    private javax.swing.JButton buttonEskul;
    private javax.swing.JButton buttonSaveData;
    private javax.swing.JButton buttonSaveData1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane tabelSiswaAktif;
    private javax.swing.JTable tableSiswaAktif;
    private javax.swing.JTextField txtJenisExtra;
    // End of variables declaration//GEN-END:variables
}
