/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package framePackage;

import classPackage.aboutClass;
import static framePackage.mainFrame.contentPanel;

/**
 *
 * @author ASUS
 */
public class dashboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form dashboardPanel
     */
    public dashboardPanel() {
        initComponents();
        jumlahAll();
    }
    
    void jumlahAll(){
        aboutClass about = new aboutClass();
        
        LabelKelas.setText(about.jumlahKelas());
        LabelEkstra.setText(about.jumlahEkstra());
        LabelPembina.setText(about.jumlahPembina());
        LabelSiswa.setText(about.jumlahSiswa());
        LabelPengguna.setText(about.namaPengguna());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        labelInfoKelas = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LabelKelas = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        LabelPembina = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelInfoPembina = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        LabelEkstra = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        labelInfoEkstra = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        LabelSiswa = new javax.swing.JLabel();
        labelInfoSiswa = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        LabelPengguna = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 123, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("KELAS");
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));

        labelInfoKelas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelInfoKelas.setForeground(new java.awt.Color(255, 255, 255));
        labelInfoKelas.setText("MORE INFO");
        labelInfoKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelInfoKelasMouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPackage/icons8-class-64.png"))); // NOI18N

        LabelKelas.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LabelKelas.setForeground(new java.awt.Color(255, 255, 255));
        LabelKelas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelKelas.setText("0  ");
        LabelKelas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        LabelKelas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addComponent(labelInfoKelas)
                .addGap(210, 210, 210))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelKelas))
                    .addComponent(jLabel7))
                .addGap(13, 13, 13)
                .addComponent(labelInfoKelas)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(40, 167, 69));

        LabelPembina.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LabelPembina.setForeground(new java.awt.Color(255, 255, 255));
        LabelPembina.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelPembina.setText("0  ");
        LabelPembina.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PEMBINA");
        jLabel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));

        labelInfoPembina.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelInfoPembina.setForeground(new java.awt.Color(255, 255, 255));
        labelInfoPembina.setText("MORE INFO");
        labelInfoPembina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelInfoPembinaMouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPackage/icons8-training-64.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(LabelPembina, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelInfoPembina)
                .addGap(204, 204, 204))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelPembina))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelInfoPembina)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(253, 126, 20));

        LabelEkstra.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LabelEkstra.setForeground(new java.awt.Color(255, 255, 255));
        LabelEkstra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelEkstra.setText("0  ");
        LabelEkstra.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        LabelEkstra.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("EKSTRAKURIKULER");
        jLabel13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));

        labelInfoEkstra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelInfoEkstra.setForeground(new java.awt.Color(255, 255, 255));
        labelInfoEkstra.setText("MORE INFO");
        labelInfoEkstra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelInfoEkstraMouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPackage/icons8-extracurricular-activities-64.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(LabelEkstra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelInfoEkstra)
                .addGap(204, 204, 204))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelEkstra))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(labelInfoEkstra)
                .addGap(21, 21, 21))
        );

        jPanel2.setBackground(new java.awt.Color(23, 162, 184));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("SISWA AKTIF");
        jLabel14.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));

        LabelSiswa.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LabelSiswa.setForeground(new java.awt.Color(255, 255, 255));
        LabelSiswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelSiswa.setText("0  ");
        LabelSiswa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        LabelSiswa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        labelInfoSiswa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelInfoSiswa.setForeground(new java.awt.Color(255, 255, 255));
        labelInfoSiswa.setText("MORE INFO");
        labelInfoSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelInfoSiswaMouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPackage/icons8-auditorium-64.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(LabelSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelInfoSiswa)
                .addGap(203, 203, 203))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(12, 12, 12)
                        .addComponent(LabelSiswa))
                    .addComponent(jLabel9))
                .addGap(11, 11, 11)
                .addComponent(labelInfoSiswa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(30, 58, 138));

        LabelPengguna.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        LabelPengguna.setForeground(new java.awt.Color(255, 255, 255));
        LabelPengguna.setText("PENGGUNA");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SELAMAT DATANG");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelPengguna)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LabelPengguna))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(159, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void labelInfoKelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelInfoKelasMouseClicked
        // TODO add your handling code here:
        contentPanel.removeAll();
        contentPanel.add(new kelasPanel());
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_labelInfoKelasMouseClicked

    private void labelInfoPembinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelInfoPembinaMouseClicked
        // TODO add your handling code here:
        contentPanel.removeAll();
        contentPanel.add(new pembinaPanel());
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_labelInfoPembinaMouseClicked

    private void labelInfoEkstraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelInfoEkstraMouseClicked
        // TODO add your handling code here:
        contentPanel.removeAll();
        contentPanel.add(new ekstraPanel());
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_labelInfoEkstraMouseClicked

    private void labelInfoSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelInfoSiswaMouseClicked
        // TODO add your handling code here:
        contentPanel.removeAll();
        contentPanel.add(new dataSiswaAktifPanel());
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_labelInfoSiswaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelEkstra;
    private javax.swing.JLabel LabelKelas;
    private javax.swing.JLabel LabelPembina;
    private javax.swing.JLabel LabelPengguna;
    private javax.swing.JLabel LabelSiswa;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel labelInfoEkstra;
    private javax.swing.JLabel labelInfoKelas;
    private javax.swing.JLabel labelInfoPembina;
    private javax.swing.JLabel labelInfoSiswa;
    // End of variables declaration//GEN-END:variables
}
