/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package framePackage;

import static framePackage.mainFrame.contentPanel;
import classPackage.siswaClass;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class dataSiswaNonAktifPanel extends javax.swing.JPanel {

    /**
     * Creates new form dataSiswaNonAktifPanel
     */
    public dataSiswaNonAktifPanel() {
        initComponents();
        dataTidakAktif();
    }

    static String isMode = "Tidak Aktif";

    void dataTidakAktif() {
        DefaultTableModel model = new DefaultTableModel();
        siswaClass dataSiswa = new siswaClass();

        model.addColumn("NISN");
        model.addColumn("Nama Siswa");
        model.addColumn("Kelas");
        model.addColumn("Ekstrakurikuler");

        try {
            ResultSet rsVar = dataSiswa.showSimpleDataNonAktif("Tidak Aktif");

            while (rsVar.next()) {
                String nisn = rsVar.getString("nisn");
                String nama = rsVar.getString("nama");
                String kelass = rsVar.getString("nama_kelas");
                String ekstra = rsVar.getString("nama_ekstra");

                Object[] data = {nisn, nama, kelass, ekstra};
                model.addRow(data);
            }

            tableNonAktif.setModel(model);
        } catch (SQLException sQLException) {
        }
    }

    void dataPurna() {
        DefaultTableModel model = new DefaultTableModel();
        siswaClass dataC = new siswaClass();

        model.addColumn("NISN");
        model.addColumn("Nama Siswa");
        model.addColumn("Kelas");
        model.addColumn("Ekstrakurikuler");

        try {
            ResultSet rsVar = dataC.showSimpleDataNonAktif("Purna");

            while (rsVar.next()) {
                String nisn = rsVar.getString("nisn");
                String nama = rsVar.getString("nama");
                String kelass = rsVar.getString("nama_kelas");
                String ekstra = rsVar.getString("nama_ekstra");

                Object[] data = {nisn, nama, kelass, ekstra};
                model.addRow(data);
            }

            tableNonAktif.setModel(model);
        } catch (SQLException sQLException) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPurna = new javax.swing.JButton();
        buttonTidakAktif = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNonAktif = new javax.swing.JTable();
        buttonKembali = new javax.swing.JButton();
        buttonSaveData = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        buttonPurna.setBackground(new java.awt.Color(102, 102, 102));
        buttonPurna.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonPurna.setForeground(new java.awt.Color(255, 255, 255));
        buttonPurna.setText("DATA PURNA");
        buttonPurna.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonPurna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPurnaActionPerformed(evt);
            }
        });

        buttonTidakAktif.setBackground(new java.awt.Color(40, 167, 69));
        buttonTidakAktif.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonTidakAktif.setForeground(new java.awt.Color(255, 255, 255));
        buttonTidakAktif.setText("DATA TIDAK AKTIF");
        buttonTidakAktif.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonTidakAktif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTidakAktifActionPerformed(evt);
            }
        });

        tableNonAktif.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableNonAktif);

        buttonKembali.setBackground(new java.awt.Color(108, 117, 125));
        buttonKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonKembali.setForeground(new java.awt.Color(255, 255, 255));
        buttonKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPackage/icons8-back-24.png"))); // NOI18N
        buttonKembali.setText("KEMBALI");
        buttonKembali.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });

        buttonSaveData.setBackground(new java.awt.Color(40, 167, 69));
        buttonSaveData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonSaveData.setForeground(new java.awt.Color(255, 255, 255));
        buttonSaveData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPackage/icons8-save-as-24.png"))); // NOI18N
        buttonSaveData.setText("SIMPAN DATA");
        buttonSaveData.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonSaveData.setIconTextGap(8);
        buttonSaveData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveDataActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(30, 58, 138));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DATA SISWA NON-AKTIF");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8)
                .addContainerGap(977, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(buttonSaveData, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonTidakAktif, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(buttonPurna, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTidakAktif, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPurna, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSaveData, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTidakAktifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTidakAktifActionPerformed
        // TODO add your handling code here:
        isMode = "Tidak Aktif";
        buttonTidakAktif.setBackground(new java.awt.Color(40, 167, 69));
        buttonPurna.setBackground(new java.awt.Color(102, 102, 102));
        dataTidakAktif();
    }//GEN-LAST:event_buttonTidakAktifActionPerformed

    private void buttonPurnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPurnaActionPerformed
        // TODO add your handling code here:
        isMode = "Purna";
        buttonTidakAktif.setBackground(new java.awt.Color(102, 102, 102));
        buttonPurna.setBackground(new java.awt.Color(40, 167, 69));
        dataPurna();
    }//GEN-LAST:event_buttonPurnaActionPerformed

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        // TODO add your handling code here:
        contentPanel.removeAll();
        contentPanel.add(new kelolaSiswaNonAktifPanel());
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_buttonKembaliActionPerformed

    private void buttonSaveDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveDataActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Menyimpan Data Siswa " + isMode);

        int userSelection = chooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {

            File fileToSave = chooser.getSelectedFile();

            try {

                Document document = new Document();
                com.itextpdf.text.pdf.PdfWriter.getInstance(document, new FileOutputStream(fileToSave.getAbsolutePath() + ".pdf"));
                document.open();

                //Font untuk header dan isi
                Font fontHeader = new Font(Font.FontFamily.HELVETICA, 9, Font.BOLD);
                Font fontCell = new Font(Font.FontFamily.HELVETICA, 8);

                //Tambahkan judul
                Paragraph title;

                if (isMode.equalsIgnoreCase("Tidak Aktif")) {
                    title = new Paragraph("Daftar Siswa Tidak Aktif".toUpperCase(), new Font(Font.FontFamily.HELVETICA, 14, Font.BOLD));
                } else {
                    title = new Paragraph("Daftar Siswa Purna".toUpperCase(), new Font(Font.FontFamily.HELVETICA, 14, Font.BOLD));
                }

                Paragraph tanggal = new Paragraph("Data diakses pada :  " + mainFrame.labelWaktu.getText(), new Font(Font.FontFamily.HELVETICA, 10, Font.NORMAL));

                title.setAlignment(Element.ALIGN_CENTER);
                document.add(title);
                document.add(new Paragraph(" ")); // spasi
                document.add(new Paragraph(" "));
                document.add(new Paragraph(tanggal));

                //buat tabel PDF sesuai jumlah kolom JTable
                PdfPTable pdfTable = new PdfPTable(tableNonAktif.getColumnCount());
                pdfTable.setWidthPercentage(100); // tabel full width
                pdfTable.setSpacingBefore(10f);
                pdfTable.setSpacingAfter(10f);

                //Header kolom
                for (int i = 0; i < tableNonAktif.getColumnCount(); i++) {
                    PdfPCell cell = new PdfPCell(new Phrase(tableNonAktif.getColumnName(i), fontHeader));
                    cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                    cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
                    cell.setPaddingTop(5);
                    cell.setPaddingBottom(5);
                    pdfTable.addCell(cell);
                }

                //Isi tabel
                for (int row = 0; row < tableNonAktif.getRowCount(); row++) {
                    for (int col = 0; col < tableNonAktif.getColumnCount(); col++) {
                        Object value = tableNonAktif.getValueAt(row, col);
                        PdfPCell cell = new PdfPCell(new Phrase(value == null ? "" : value.toString(), fontCell));
                        cell.setHorizontalAlignment(Element.ALIGN_LEFT);
                        cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
                        cell.setPaddingLeft(3);
                        cell.setPaddingTop(5);
                        cell.setPaddingRight(3);
                        cell.setPaddingBottom(5);
                        pdfTable.addCell(cell);
                    }
                }

                document.add(pdfTable);
                document.close();

                JOptionPane.showMessageDialog(this, "Data berhasil disimpan ke PDF:\n" + fileToSave.getAbsolutePath() + ".pdf");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan PDF: " + e.getMessage());
            }
        }

    }//GEN-LAST:event_buttonSaveDataActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonKembali;
    private javax.swing.JButton buttonPurna;
    private javax.swing.JButton buttonSaveData;
    private javax.swing.JButton buttonTidakAktif;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableNonAktif;
    // End of variables declaration//GEN-END:variables
}
