/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package framePackage;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author ASUS
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        waktu();
        runningText();
    }

    
    void waktu(){
        Calendar calendar = Calendar.getInstance();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        SimpleDateFormat dayFormat = new SimpleDateFormat("EEEE", new Locale("in", "ID"));
        
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String day = dayFormat.format(calendar.getTime());
                String dateTime = dateFormat.format(new Date());
                labelWaktu.setText(day + ",  " + dateTime);
            }
        });
        timer.start();
    }
    
    

    SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
    Date date = new Date();
    int jumlahSpasi = 190;
    String spasi = " ".repeat(jumlahSpasi);
    String text = spasi + "Selamat datang di Aplikasi SI-EKSTRA Sistem Ekstrakurikuler, untuk mengembangkan minat dan bakat siswa di intuisi pendidikan. Aplikasi SI-EKSTRA dapat membantu memanajemen pendataan siswa yang aktif mengikuti Ekstrakurikuler.  -  " + dateFormat.format(date);
    void runningText() {

        Timer timer = new Timer(100, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                text = text.substring(1) + text.charAt(0);
                runningTextLabel.setText(text);
            }
        });
        timer.start();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidebarPanel = new javax.swing.JPanel();
        buttonDashboard = new javax.swing.JButton();
        buttonKelas = new javax.swing.JButton();
        buttonEkstrakurikuler = new javax.swing.JButton();
        buttonFormSiswa = new javax.swing.JButton();
        buttonDataSiswaAktif = new javax.swing.JButton();
        buttonDataSiswaNonAktif = new javax.swing.JButton();
        buttonStatitiskaTabel = new javax.swing.JButton();
        buttonKeamananUser = new javax.swing.JButton();
        buttonAbout = new javax.swing.JButton();
        buttonLogout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        navbarPanel = new javax.swing.JPanel();
        labelClose = new javax.swing.JLabel();
        runningTextLabel = new javax.swing.JLabel();
        labelWaktu = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        sidebarPanel.setBackground(new java.awt.Color(30, 58, 138));

        buttonDashboard.setBackground(new java.awt.Color(30, 58, 138));
        buttonDashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonDashboard.setForeground(new java.awt.Color(255, 255, 255));
        buttonDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framePackage/images/icons8-dashboard-layout-24.png"))); // NOI18N
        buttonDashboard.setText("DASHBOARD");
        buttonDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        buttonDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonDashboard.setIconTextGap(8);

        buttonKelas.setBackground(new java.awt.Color(30, 58, 138));
        buttonKelas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonKelas.setForeground(new java.awt.Color(255, 255, 255));
        buttonKelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framePackage/images/icons8-class-24.png"))); // NOI18N
        buttonKelas.setText("KELAS");
        buttonKelas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        buttonKelas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonKelas.setIconTextGap(8);

        buttonEkstrakurikuler.setBackground(new java.awt.Color(30, 58, 138));
        buttonEkstrakurikuler.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonEkstrakurikuler.setForeground(new java.awt.Color(255, 255, 255));
        buttonEkstrakurikuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framePackage/images/icons8-talent-24.png"))); // NOI18N
        buttonEkstrakurikuler.setText("EKSTRAKURIKULER");
        buttonEkstrakurikuler.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        buttonEkstrakurikuler.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonEkstrakurikuler.setIconTextGap(8);

        buttonFormSiswa.setBackground(new java.awt.Color(30, 58, 138));
        buttonFormSiswa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonFormSiswa.setForeground(new java.awt.Color(255, 255, 255));
        buttonFormSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framePackage/images/icons8-person-24.png"))); // NOI18N
        buttonFormSiswa.setText("FORM SISWA");
        buttonFormSiswa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        buttonFormSiswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonFormSiswa.setIconTextGap(8);
        buttonFormSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFormSiswaActionPerformed(evt);
            }
        });

        buttonDataSiswaAktif.setBackground(new java.awt.Color(30, 58, 138));
        buttonDataSiswaAktif.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonDataSiswaAktif.setForeground(new java.awt.Color(255, 255, 255));
        buttonDataSiswaAktif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framePackage/images/icons8-active-24.png"))); // NOI18N
        buttonDataSiswaAktif.setText("DATA SISWA AKTIF");
        buttonDataSiswaAktif.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        buttonDataSiswaAktif.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonDataSiswaAktif.setIconTextGap(8);

        buttonDataSiswaNonAktif.setBackground(new java.awt.Color(30, 58, 138));
        buttonDataSiswaNonAktif.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonDataSiswaNonAktif.setForeground(new java.awt.Color(255, 255, 255));
        buttonDataSiswaNonAktif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framePackage/images/icons8-indeterminate-checkbox-24.png"))); // NOI18N
        buttonDataSiswaNonAktif.setText("DATA SISWA NON-AKTIF");
        buttonDataSiswaNonAktif.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        buttonDataSiswaNonAktif.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonDataSiswaNonAktif.setIconTextGap(8);

        buttonStatitiskaTabel.setBackground(new java.awt.Color(30, 58, 138));
        buttonStatitiskaTabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonStatitiskaTabel.setForeground(new java.awt.Color(255, 255, 255));
        buttonStatitiskaTabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framePackage/images/icons8-website-statistics-24.png"))); // NOI18N
        buttonStatitiskaTabel.setText("STATITISKA TABEL");
        buttonStatitiskaTabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        buttonStatitiskaTabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonStatitiskaTabel.setIconTextGap(8);
        buttonStatitiskaTabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStatitiskaTabelActionPerformed(evt);
            }
        });

        buttonKeamananUser.setBackground(new java.awt.Color(30, 58, 138));
        buttonKeamananUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonKeamananUser.setForeground(new java.awt.Color(255, 255, 255));
        buttonKeamananUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framePackage/images/icons8-secure-24.png"))); // NOI18N
        buttonKeamananUser.setText("KEAMANAN USER");
        buttonKeamananUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        buttonKeamananUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonKeamananUser.setIconTextGap(8);

        buttonAbout.setBackground(new java.awt.Color(30, 58, 138));
        buttonAbout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonAbout.setForeground(new java.awt.Color(255, 255, 255));
        buttonAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framePackage/images/icons8-about-24.png"))); // NOI18N
        buttonAbout.setText("ABOUT");
        buttonAbout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        buttonAbout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonAbout.setIconTextGap(8);

        buttonLogout.setBackground(new java.awt.Color(30, 58, 138));
        buttonLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonLogout.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framePackage/images/icons8-logout-24.png"))); // NOI18N
        buttonLogout.setText("LOGOUT");
        buttonLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        buttonLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonLogout.setIconTextGap(8);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SISTEM EKSTRAKURIKULER");

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonKelas, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addComponent(buttonEkstrakurikuler, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addComponent(buttonFormSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addComponent(buttonDataSiswaAktif, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addComponent(buttonDataSiswaNonAktif, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addComponent(buttonStatitiskaTabel, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addComponent(buttonKeamananUser, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addComponent(buttonAbout, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addComponent(buttonLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel4)
                .addGap(56, 56, 56)
                .addComponent(buttonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonEkstrakurikuler, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonFormSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonDataSiswaAktif, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonDataSiswaNonAktif, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonStatitiskaTabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonKeamananUser, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        navbarPanel.setBackground(new java.awt.Color(37, 99, 235));

        labelClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framePackage/images/icons8-close-40.png"))); // NOI18N
        labelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCloseMouseClicked(evt);
            }
        });

        runningTextLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        runningTextLabel.setForeground(new java.awt.Color(255, 255, 255));
        runningTextLabel.setText("jLabel2");

        labelWaktu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelWaktu.setForeground(new java.awt.Color(255, 255, 255));
        labelWaktu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framePackage/images/icons8-dashboard2-24.png"))); // NOI18N
        labelWaktu.setText("Day, 00-00-0000 00:00:00");
        labelWaktu.setIconTextGap(10);

        javax.swing.GroupLayout navbarPanelLayout = new javax.swing.GroupLayout(navbarPanel);
        navbarPanel.setLayout(navbarPanelLayout);
        navbarPanelLayout.setHorizontalGroup(
            navbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navbarPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(runningTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelWaktu)
                .addGap(70, 70, 70)
                .addComponent(labelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        navbarPanelLayout.setVerticalGroup(
            navbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarPanelLayout.createSequentialGroup()
                .addGroup(navbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navbarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelClose))
                    .addGroup(navbarPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(navbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(runningTextLabel)
                            .addComponent(labelWaktu))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        contentPanel.setBackground(new java.awt.Color(204, 204, 204));
        contentPanel.setLayout(new java.awt.CardLayout(1, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1144, Short.MAX_VALUE)
                    .addComponent(navbarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navbarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_labelCloseMouseClicked

    private void buttonFormSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFormSiswaActionPerformed
        // TODO add your handling code here:
        contentPanel.removeAll();
        contentPanel.add(new siswaPanel());
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_buttonFormSiswaActionPerformed

    private void buttonStatitiskaTabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStatitiskaTabelActionPerformed
        // TODO add your handling code here:
        contentPanel.removeAll();
        contentPanel.add(new statiskaPanel());
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_buttonStatitiskaTabelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAbout;
    private javax.swing.JButton buttonDashboard;
    private javax.swing.JButton buttonDataSiswaAktif;
    private javax.swing.JButton buttonDataSiswaNonAktif;
    private javax.swing.JButton buttonEkstrakurikuler;
    private javax.swing.JButton buttonFormSiswa;
    private javax.swing.JButton buttonKeamananUser;
    private javax.swing.JButton buttonKelas;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonStatitiskaTabel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelClose;
    private javax.swing.JLabel labelWaktu;
    private javax.swing.JPanel navbarPanel;
    private javax.swing.JLabel runningTextLabel;
    private javax.swing.JPanel sidebarPanel;
    // End of variables declaration//GEN-END:variables
}
