/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package framePackage;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author ASUS
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        waktu();
        runningText();
        
    }

    
    void waktu(){
        Calendar calendar = Calendar.getInstance();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        SimpleDateFormat dayFormat = new SimpleDateFormat("EEEE", new Locale("in", "ID"));
        
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String day = dayFormat.format(calendar.getTime());
                String dateTime = dateFormat.format(new Date());
                labelWaktu.setText(day + ",  " + dateTime);
            }
        });
        timer.start();
    }
    
    

    SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
    Date date = new Date();
    int jumlahSpasi = 190;
    String spasi = " ".repeat(jumlahSpasi);
    String text = spasi + "Selamat datang di Aplikasi SI-EKSTRA Sistem Ekstrakurikuler, untuk mengembangkan minat dan bakat siswa di intuisi pendidikan. Aplikasi SI-EKSTRA dapat membantu memanajemen pendataan siswa yang aktif mengikuti Ekstrakurikuler.  -  " + dateFormat.format(date);
    void runningText() {

        Timer timer = new Timer(100, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                text = text.substring(1) + text.charAt(0);
                runningTextLabel.setText(text);
            }
        });
        timer.start();
    }

  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        sidebarPanel = new javax.swing.JPanel();
        buttonDashboard = new javax.swing.JButton();
        buttonKelas = new javax.swing.JButton();
        buttonEkstra = new javax.swing.JButton();
        buttonFormSiswa = new javax.swing.JButton();
        buttonSiswaAktif = new javax.swing.JButton();
        buttonSiswaNonAktif = new javax.swing.JButton();
        buttonStatistikTabel = new javax.swing.JButton();
        buttonKeamanan = new javax.swing.JButton();
        buttonAbout = new javax.swing.JButton();
        buttonLogout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonPembina = new javax.swing.JButton();
        navbarPanel = new javax.swing.JPanel();
        labelClose = new javax.swing.JLabel();
        runningTextLabel = new javax.swing.JLabel();
        labelWaktu = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        sidebarPanel.setBackground(new java.awt.Color(30, 58, 138));

        buttonDashboard.setBackground(new java.awt.Color(30, 58, 138));
        buttonDashboard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonDashboard.setForeground(new java.awt.Color(255, 255, 255));
        buttonDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framePackage/images/icons8-dashboard-layout-24.png"))); // NOI18N
        buttonDashboard.setText("DASHBOARD");
        buttonDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        buttonDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonDashboard.setIconTextGap(8);
        buttonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDashboardActionPerformed(evt);
            }
        });

        buttonKelas.setBackground(new java.awt.Color(30, 58, 138));
        buttonKelas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonKelas.setForeground(new java.awt.Color(255, 255, 255));
        buttonKelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framePackage/images/icons8-class-24.png"))); // NOI18N
        buttonKelas.setText("KELAS");
        buttonKelas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        buttonKelas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonKelas.setIconTextGap(8);
        buttonKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKelasActionPerformed(evt);
            }
        });

        buttonEkstra.setBackground(new java.awt.Color(30, 58, 138));
        buttonEkstra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonEkstra.setForeground(new java.awt.Color(255, 255, 255));
        buttonEkstra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framePackage/images/icons8-talent-24.png"))); // NOI18N
        buttonEkstra.setText("EKSTRAKURIKULER");
        buttonEkstra.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        buttonEkstra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonEkstra.setIconTextGap(8);
        buttonEkstra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEkstraActionPerformed(evt);
            }
        });

        buttonFormSiswa.setBackground(new java.awt.Color(30, 58, 138));
        buttonFormSiswa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonFormSiswa.setForeground(new java.awt.Color(255, 255, 255));
        buttonFormSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framePackage/images/icons8-form-24.png"))); // NOI18N
        buttonFormSiswa.setText("FORM SISWA");
        buttonFormSiswa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        buttonFormSiswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonFormSiswa.setIconTextGap(8);
        buttonFormSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFormSiswaActionPerformed(evt);
            }
        });

        buttonSiswaAktif.setBackground(new java.awt.Color(30, 58, 138));
        buttonSiswaAktif.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonSiswaAktif.setForeground(new java.awt.Color(255, 255, 255));
        buttonSiswaAktif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framePackage/images/icons8-active-24.png"))); // NOI18N
        buttonSiswaAktif.setText("DATA SISWA AKTIF");
        buttonSiswaAktif.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        buttonSiswaAktif.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonSiswaAktif.setIconTextGap(8);
        buttonSiswaAktif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSiswaAktifActionPerformed(evt);
            }
        });

        buttonSiswaNonAktif.setBackground(new java.awt.Color(30, 58, 138));
        buttonSiswaNonAktif.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonSiswaNonAktif.setForeground(new java.awt.Color(255, 255, 255));
        buttonSiswaNonAktif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framePackage/images/icons8-indeterminate-checkbox-24.png"))); // NOI18N
        buttonSiswaNonAktif.setText("DATA SISWA NON-AKTIF");
        buttonSiswaNonAktif.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        buttonSiswaNonAktif.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonSiswaNonAktif.setIconTextGap(8);
        buttonSiswaNonAktif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSiswaNonAktifActionPerformed(evt);
            }
        });

        buttonStatistikTabel.setBackground(new java.awt.Color(30, 58, 138));
        buttonStatistikTabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonStatistikTabel.setForeground(new java.awt.Color(255, 255, 255));
        buttonStatistikTabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framePackage/images/icons8-website-statistics-24.png"))); // NOI18N
        buttonStatistikTabel.setText("STATISTIK TABEL");
        buttonStatistikTabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        buttonStatistikTabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonStatistikTabel.setIconTextGap(8);
        buttonStatistikTabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStatistikTabelActionPerformed(evt);
            }
        });

        buttonKeamanan.setBackground(new java.awt.Color(30, 58, 138));
        buttonKeamanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonKeamanan.setForeground(new java.awt.Color(255, 255, 255));
        buttonKeamanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framePackage/images/icons8-secure-24.png"))); // NOI18N
        buttonKeamanan.setText("KEAMANAN");
        buttonKeamanan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        buttonKeamanan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonKeamanan.setIconTextGap(8);
        buttonKeamanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeamananActionPerformed(evt);
            }
        });

        buttonAbout.setBackground(new java.awt.Color(30, 58, 138));
        buttonAbout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonAbout.setForeground(new java.awt.Color(255, 255, 255));
        buttonAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framePackage/images/icons8-about-24.png"))); // NOI18N
        buttonAbout.setText("ABOUT");
        buttonAbout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        buttonAbout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonAbout.setIconTextGap(8);
        buttonAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAboutActionPerformed(evt);
            }
        });

        buttonLogout.setBackground(new java.awt.Color(30, 58, 138));
        buttonLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonLogout.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framePackage/images/icons8-logout-24.png"))); // NOI18N
        buttonLogout.setText("LOGOUT");
        buttonLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        buttonLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonLogout.setIconTextGap(8);
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framePackage/images/SI-EKSTRA 144.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SISTEM EKSTRAKURIKULER");

        buttonPembina.setBackground(new java.awt.Color(30, 58, 138));
        buttonPembina.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonPembina.setForeground(new java.awt.Color(255, 255, 255));
        buttonPembina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framePackage/images/icons8-person-24.png"))); // NOI18N
        buttonPembina.setText("PEMBINA");
        buttonPembina.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        buttonPembina.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonPembina.setIconTextGap(8);
        buttonPembina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPembinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonEkstra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonFormSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonSiswaAktif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonSiswaNonAktif, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addComponent(buttonStatistikTabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonKeamanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonAbout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(buttonPembina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addComponent(buttonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonPembina, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonEkstra, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonFormSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonSiswaAktif, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonSiswaNonAktif, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonStatistikTabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonKeamanan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        navbarPanel.setBackground(new java.awt.Color(37, 99, 235));

        labelClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framePackage/images/icons8-close-40.png"))); // NOI18N
        labelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCloseMouseClicked(evt);
            }
        });

        runningTextLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        runningTextLabel.setForeground(new java.awt.Color(255, 255, 255));
        runningTextLabel.setText("TEXT");

        labelWaktu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelWaktu.setForeground(new java.awt.Color(255, 255, 255));
        labelWaktu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framePackage/images/icons8-calendar-24.png"))); // NOI18N
        labelWaktu.setText("Today, 00-00-0000 00:00:00");
        labelWaktu.setIconTextGap(8);

        javax.swing.GroupLayout navbarPanelLayout = new javax.swing.GroupLayout(navbarPanel);
        navbarPanel.setLayout(navbarPanelLayout);
        navbarPanelLayout.setHorizontalGroup(
            navbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navbarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(runningTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(labelWaktu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(labelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        navbarPanelLayout.setVerticalGroup(
            navbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarPanelLayout.createSequentialGroup()
                .addGroup(navbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navbarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelClose))
                    .addGroup(navbarPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(navbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(runningTextLabel)
                            .addComponent(labelWaktu))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        contentPanel.setBackground(new java.awt.Color(204, 204, 204));
        contentPanel.setLayout(new java.awt.CardLayout(1, 1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navbarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navbarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCloseMouseClicked
        // TODO add your handling code here:
        int yesOrNo = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (yesOrNo == JOptionPane.YES_OPTION) {
            dispose();
            new loginFrame().setVisible(true);
        }
    }//GEN-LAST:event_labelCloseMouseClicked

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        // TODO add your handling code here:
        int yesOrNo = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (yesOrNo == JOptionPane.YES_OPTION) {
            dispose();
            new loginFrame().setVisible(true);
        }
    }//GEN-LAST:event_buttonLogoutActionPerformed

    private void buttonFormSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFormSiswaActionPerformed
        // TODO add your handling code here:
        contentPanel.removeAll();
        contentPanel.add(new siswaPanel());
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_buttonFormSiswaActionPerformed

    private void buttonStatistikTabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStatistikTabelActionPerformed
        // TODO add your handling code here:
        contentPanel.removeAll();
        contentPanel.add(new statistikPanel());
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_buttonStatistikTabelActionPerformed

    private void buttonKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKelasActionPerformed
        // TODO add your handling code here:
        contentPanel.removeAll();
        contentPanel.add(new kelasPanel());
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_buttonKelasActionPerformed

    private void buttonEkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEkstraActionPerformed
        // TODO add your handling code here:
        contentPanel.removeAll();
        contentPanel.add(new ekstraPanel());
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_buttonEkstraActionPerformed

    private void buttonPembinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPembinaActionPerformed
        // TODO add your handling code here:
        contentPanel.removeAll();
        contentPanel.add(new pembinaPanel());
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_buttonPembinaActionPerformed

    private void buttonSiswaAktifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSiswaAktifActionPerformed
        // TODO add your handling code here:
         contentPanel.removeAll();
        contentPanel.add(new dataSiswaAktifPanel());
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_buttonSiswaAktifActionPerformed

    private void buttonSiswaNonAktifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSiswaNonAktifActionPerformed
        // TODO add your handling code here:
        contentPanel.removeAll();
        contentPanel.add(new kelolaSiswaNonAktifPanel());
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_buttonSiswaNonAktifActionPerformed

    private void buttonKeamananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeamananActionPerformed
        // TODO add your handling code here:
        contentPanel.removeAll();
        contentPanel.add(new keamananPanel());
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_buttonKeamananActionPerformed

    private void buttonAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAboutActionPerformed
        // TODO add your handling code here:
        contentPanel.removeAll();
        contentPanel.add(new aboutPanel());
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_buttonAboutActionPerformed

    private void buttonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDashboardActionPerformed
        // TODO add your handling code here:
        contentPanel.removeAll();
        contentPanel.add(new dashboardPanel());
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_buttonDashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAbout;
    private javax.swing.JButton buttonDashboard;
    private javax.swing.JButton buttonEkstra;
    private javax.swing.JButton buttonFormSiswa;
    private javax.swing.JButton buttonKeamanan;
    private javax.swing.JButton buttonKelas;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonPembina;
    private javax.swing.JButton buttonSiswaAktif;
    private javax.swing.JButton buttonSiswaNonAktif;
    private javax.swing.JButton buttonStatistikTabel;
    public static javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelClose;
    private javax.swing.JLabel labelWaktu;
    private javax.swing.JPanel navbarPanel;
    private javax.swing.JLabel runningTextLabel;
    private javax.swing.JPanel sidebarPanel;
    // End of variables declaration//GEN-END:variables
}
