/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package framePackage;

import classPackage.siswaClass;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import static framePackage.mainFrame.contentPanel;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class presensiPanel extends javax.swing.JPanel {

    /**
     * Creates new form absensiPanel
     */
    public presensiPanel() {
        initComponents();
        loadDataAll();
    }

    void loadDataAll() {
        try {
            siswaClass dataAbsen = new siswaClass();
            DefaultTableModel model = dataAbsen.showDataAbsensiAll();
            tablePresensi.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error : " + e.getMessage());
        }
    }

    void loadDataCategory() {
        try {
            siswaClass dataAbsen = new siswaClass();
            DefaultTableModel model = dataAbsen.showDataAbsensiKategori(txtJenisExtra.getText());
            tablePresensi.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error : " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        buttonCariData = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtJenisExtra = new javax.swing.JTextField();
        buttonEskul = new javax.swing.JButton();
        buttonCetak = new javax.swing.JButton();
        JScrollPane = new javax.swing.JScrollPane();
        tablePresensi = new javax.swing.JTable();
        buttonKembali = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(30, 58, 138));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PRESENSI SISWA AKTIF");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        buttonCariData.setBackground(new java.awt.Color(102, 16, 242));
        buttonCariData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonCariData.setForeground(new java.awt.Color(255, 255, 255));
        buttonCariData.setText("CARI DATA");
        buttonCariData.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonCariData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariDataActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("JENIS EKSTRAKURIKULER");

        txtJenisExtra.setEditable(false);
        txtJenisExtra.setBackground(new java.awt.Color(204, 204, 204));
        txtJenisExtra.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txtJenisExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisExtraActionPerformed(evt);
            }
        });

        buttonEskul.setBackground(new java.awt.Color(111, 66, 193));
        buttonEskul.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonEskul.setForeground(new java.awt.Color(255, 255, 255));
        buttonEskul.setText("PILIH EKSTRAKURIKULER");
        buttonEskul.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonEskul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEskulActionPerformed(evt);
            }
        });

        buttonCetak.setBackground(new java.awt.Color(40, 167, 69));
        buttonCetak.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonCetak.setForeground(new java.awt.Color(255, 255, 255));
        buttonCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPackage/icons8-save-as-24.png"))); // NOI18N
        buttonCetak.setText("CETAK PRESENSI");
        buttonCetak.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonCetak.setIconTextGap(8);
        buttonCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCetakActionPerformed(evt);
            }
        });

        tablePresensi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JScrollPane.setViewportView(tablePresensi);

        buttonKembali.setBackground(new java.awt.Color(108, 117, 125));
        buttonKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonKembali.setForeground(new java.awt.Color(255, 255, 255));
        buttonKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPackage/icons8-back-24.png"))); // NOI18N
        buttonKembali.setText("KEMBALI");
        buttonKembali.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtJenisExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonEskul, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonCariData, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(buttonKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(buttonCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonEskul, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonCariData, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtJenisExtra))
                .addGap(40, 40, 40)
                .addComponent(JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCariDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariDataActionPerformed
        // TODO add your handling code here:
        if (txtJenisExtra.getText().isEmpty()) {
            loadDataAll();
        } else {
            loadDataCategory();
        }
    }//GEN-LAST:event_buttonCariDataActionPerformed

    private void txtJenisExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisExtraActionPerformed
        // TODO add your handling code here:
        if (txtJenisExtra.getText().isEmpty()) {
            loadDataAll();
        } else {
            loadDataCategory();
        }
    }//GEN-LAST:event_txtJenisExtraActionPerformed

    private void buttonEskulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEskulActionPerformed
        // TODO add your handling code here:
        new dataEkstraForPresensiFrame().setVisible(true);
    }//GEN-LAST:event_buttonEskulActionPerformed

    private void buttonCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCetakActionPerformed
        // TODO add your handling code here:
        int jumlahSpasi = 100;
        String spasi = ".".repeat(jumlahSpasi);
        
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Menyimpan Presensi Siswa " + txtJenisExtra.getText());

        int userSelection = chooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = chooser.getSelectedFile();

            try {
                Document document = new Document();
                com.itextpdf.text.pdf.PdfWriter.getInstance(document, new FileOutputStream(fileToSave.getAbsoluteFile() + ".pdf"));
                document.open();

                //Font untuk header dan isi
                Font fontHeader = new Font(Font.FontFamily.HELVETICA, 9, Font.BOLD);
                Font fontCell = new Font(Font.FontFamily.HELVETICA, 8);

                //Tambahkan Judul
                Paragraph title = new Paragraph("Presensi Ekstrakurikuler ".toUpperCase() + txtJenisExtra.getText().toUpperCase(), new Font(Font.FontFamily.HELVETICA, 14, Font.BOLD));
                
                Paragraph tanggal = new Paragraph("Hari / Tanggal : " + spasi, new Font(Font.FontFamily.HELVETICA, 10, Font.NORMAL));

                title.setAlignment(Element.ALIGN_CENTER);
                document.add(title);
                document.add(new Paragraph(" ")); //spasi
                document.add(new Paragraph(" ")); 
                document.add(tanggal); 
                document.add(new Paragraph(" ")); 

                //Buat tabel PDF sesuai jumlah kolom JTable
                PdfPTable pdfTable = new PdfPTable(tablePresensi.getColumnCount());
                pdfTable.setWidthPercentage(100); // tabel full width
                pdfTable.setSpacingBefore(10f);
                pdfTable.setSpacingAfter(10f);

                //Header kolom
                for (int i = 0; i < tablePresensi.getColumnCount(); i++) {
                    PdfPCell cell = new PdfPCell(new Phrase(tablePresensi.getColumnName(i), fontHeader));
                    cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                    cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
                    cell.setPaddingTop(5);
                    cell.setPaddingBottom(5);
                    pdfTable.addCell(cell);
                }
                //Isi tabel
                for (int row = 0; row < tablePresensi.getRowCount(); row++) {
                    for (int col = 0; col < tablePresensi.getColumnCount(); col++) {
                        Object value = tablePresensi.getValueAt(row, col);
                        PdfPCell cell = new PdfPCell(new Phrase(value == null ? "" : value.toString(), fontCell));

                        cell.setHorizontalAlignment(Element.ALIGN_LEFT);
                        cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
                        cell.setPaddingLeft(3);
                        cell.setPaddingTop(6);
                        cell.setPaddingRight(3);
                        cell.setPaddingBottom(6);
                        pdfTable.addCell(cell);
                    }
                }

                document.add(pdfTable);
                document.close();

                JOptionPane.showMessageDialog(this, "Data berhasil disimpan ke PDF:\n" + fileToSave.getAbsolutePath() + ".pdf");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan PDF : " + e.getMessage());
            }

        }
    }//GEN-LAST:event_buttonCetakActionPerformed

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        // TODO add your handling code here:
        contentPanel.removeAll();
        contentPanel.add(new dataSiswaAktifPanel());
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_buttonKembaliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane;
    private javax.swing.JButton buttonCariData;
    private javax.swing.JButton buttonCetak;
    private javax.swing.JButton buttonEskul;
    private javax.swing.JButton buttonKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable tablePresensi;
    public static javax.swing.JTextField txtJenisExtra;
    // End of variables declaration//GEN-END:variables
}
